version: "3.8"

services:
  be:
    build:
      context: ./be
      dockerfile: Dockerfile
    volumes:
      - ./be:/app
      - /app/node_modules
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - NODE_ENV=development
      - BACKEND_PORT=${BACKEND_PORT}
    depends_on:
      - mongo

  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
    volumes:
      - ./fe:/app
      - /app/node_modules

    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - NODE_ENV=development
      - FRONTEND_PORT=${FRONTEND_PORT}

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
